backport 1.20.6
vinceh121/Minegasm-fabric pull request #10
Opened 2024-10-30 23:15 UTC by thisaray

Closes #9

2024-10-30 23:18 UTC, thisaray commented
thought i made a mistake, didnt do one so reopen

2024-10-31 21:48 UTC, vinceh121 requested changes

2024-10-31 21:48 UTC, vinceh121 commented on src/main/resources/fabric.mod.json
> +    "modmenu": "10.0.0"
```suggestion
    "modmenu": "10.x"
```

2024-10-31 21:52 UTC, vinceh121 commented
Thank you for the backport!

I've rebased your branch and added a suggestion on the version range.

I'll merge and create the release once you've resolved the conversations.

2024-12-22 00:00 UTC, closed without merging