Update minegasm to Minecraft 1.20.4
vinceh121/Minegasm-fabric pull request #7
Opened 2024-03-27 22:24 UTC by bananasov

This PR updates Minegasm-fabric to minecraft 1.20.4 along with some changes to the `gradle.properties` file

This is my first time updating a minecraft mod so please let me know if I did anything wrong.

2024-03-30 20:10 UTC, vinceh121 requested changes
Looks good to me overall, once you've fixed the couple requests I'll happily merge your PR.

2024-03-30 20:10 UTC, vinceh121 commented on gradle.properties
> +mod_version         = 2.2.0
Please use 2.1.3

2024-03-30 20:10 UTC, vinceh121 commented on remappedSrc/com/therainbowville/minegasm/client/ClientEventHandler.java
> +package com.therainbowville.minegasm.client;
Please remove every file under remappedSrc/*

2024-04-01 10:14 UTC, bananasov commented on remappedSrc/com/therainbowville/minegasm/client/ClientEventHandler.java
> +package com.therainbowville.minegasm.client;
👍

2024-04-02 01:40 UTC, merged